@echo off
echo Stopping all Node.js processes...
taskkill /F /IM node.exe >nul 2>&1

echo Waiting for ports to release...
timeout /t 3 /nobreak >nul

echo Cleaning Next.js lock...
del /F /Q ".next\dev\lock" >nul 2>&1

echo Starting development server...
npm run dev
