import { NextResponse } from "next/server"
import nodemailer from "nodemailer"

export async function POST(req: Request) {
  try {
    const { email, studentName, marks, remarks, riskScore } = await req.json()

    if (!email || !studentName || marks === undefined) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 })
    }

    let transporter;

    if (process.env.EMAIL_USER && process.env.EMAIL_PASS) {
      transporter = nodemailer.createTransport({
        service: "gmail",
        auth: {
          user: process.env.EMAIL_USER,
          pass: process.env.EMAIL_PASS,
        },
      })
    } else {
      console.warn("Real EMAIL_USER / EMAIL_PASS not found in .env. Simulating email send instead of using real SMTP.")
      // We will skip creating a transporter and just mock the success later
    }

    const mailOptions = {
      from: `"ExamGuard AI Administration" <${process.env.EMAIL_USER || 'admin@examguard.ai'}>`,
      to: email,
      subject: `Your Exam Results & Verification Report - ExamGuard AI`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
          <div style="background-color: #0f172a; padding: 20px; border-radius: 8px 8px 0 0; text-align: center;">
            <h2 style="color: #38bdf8; margin: 0;">ExamGuard AI Dashboard</h2>
          </div>
          <div style="padding: 20px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 8px 8px;">
            <p>Dear <strong>${studentName}</strong>,</p>
            <p>Your recent examination has been successfully graded and verified by our AI monitoring systems. Below is your official performance report as evaluated by the Proctor.</p>
            
            <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; margin-top: 20px;">
              <h3 style="margin-top: 0; color: #0f172a;">Final Results</h3>
              <ul style="list-style: none; padding: 0;">
                <li style="margin-bottom: 10px; font-size: 16px;">📈 <strong>Marks Awarded:</strong> <span style="font-size: 20px; font-weight: bold; color: ${marks >= 50 ? '#10b981' : '#ef4444'};">${marks}/100</span></li>
                <li style="margin-bottom: 10px;">📋 <strong>Admin Remarks:</strong> <em>${remarks || "No additional remarks provided."}</em></li>
                <li>🛡️ <strong>Verification Integrity:</strong> Satisfactory (Behavioral Assessment: ${Number(riskScore).toFixed(1)}% Risk Deviation)</li>
              </ul>
            </div>
            
            <p style="margin-top: 20px;">If you have any questions or disputes regarding this assessment, please contact your administrator directly via the student portal.</p>
            
            <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
            <p style="font-size: 11px; color: #64748b; text-align: center;">This is an automated operational message generated by the ExamGuard AI Monitoring protocol. Please do not reply directly to this email.</p>
          </div>
        </div>
      `
    }

    let testUrl = null;

    if (transporter) {
      const info = await transporter.sendMail(mailOptions)
      console.log(`Email sent successfully to ${email} via SMTP`)
    } else {
      console.log(`[SIMULATED EMAIL] To: ${email} | Subject: ${mailOptions.subject}`)
      testUrl = "simulated-email-no-url-available"
    }

    return NextResponse.json({ 
      success: true, 
      message: transporter ? "Email sent successfully" : "Email simulated successfully",
      testUrl
    })
  } catch (error) {
    console.error("Email API Error:", error)
    return NextResponse.json({ error: "Failed to send email" }, { status: 500 })
  }
}
